apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: ${APP_NAME}
spec:
  runPolicy: Serial
  source:
    git:
      uri: ${GIT_URL}
    type: Git
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: '${IMAGE_NAME}'
parameters:
- name: GIT_URL
  description: The URL of the Git repository.
  required: true
- name: IMAGE_NAME
  description: The name of the image:tag.
  required: true
- name: APP_NAME
  description: The name of the application.
  required: true