# Description: Configuration file for the server

# repoBaseDir: The base directory where all the repositories are stored
repoBaseDir: /tmp/

# scheduler for fetching the repositories
scheduler:
  # node cron schedule every minute
  cronExpression: 0 * * * * *

# repositories to be fetched
repositories:
  - name: gitops-branch-per-env
    prUrl: https://github.com/MarcFriedhoff/${repo}/compare/${base}...${compare}?expand=1&title=${title}&body=${description}
    url: https://${GIT_USER}:${GIT_PASSWORD}@github.com/MarcFriedhoff/gitops-branch-per-env.git

# profiles for the dashboard
profiles:
  default:
    releaseTagPattern: '[0-9]+.[0-9]+.[0-9]+-rc[0-9]+-sc1'
    branchCategories:
      - name: default
        branches:
          - name: development
          - name: staging
          - name: prod
      - name: feature
        branches:
          - name: feature/.*
      - name: hotfix
        branches:
          - name: hotfix/.*
      - name: release
        branches:
          - name: release/.*
      - name: bugfix
        branches:
          - name: bugfix/.*
    deployTargets:
      - name: deve
        color: '#006400'
      - name: deve2   
        color: '#9ACD32'
      - name: intg
        color: '#CCCC00'
      - name: intg2
        color: '#FF8C00'
      - name: prep
        color: '#FF4500'
      - name: prep2
        color: '#4682B4'
      - name: lopt
        color: '#4169E1'
      - name: migr
        color: '#FF69B4'
      - name: tdbl
        color: '#FF1493'
      - name: trai
        color: '#FF0000'
      - name: hfix
        color: '#CD5C5C'
      - name: prod
        color: '#8B0000'