apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${IMAGE_NAME}-template
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: ${IMAGE_NAME}
parameters:
- name: IMAGE_NAME
  description: The name of the ImageStream.
  required: true